export const animeList = [
  {
    name: "Sousou no Frieren",
    image: "https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Fullmetal Alchemist: Brotherhood",
    image: "https://cdn.myanimelist.net/images/anime/1208/94745l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Steins;Gate",
    image: "https://cdn.myanimelist.net/images/anime/1935/127974l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama°",
    image: "https://cdn.myanimelist.net/images/anime/3/72078l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Shingeki no Kyojin Season 3 Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1517/100633l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama: The Final",
    image: "https://cdn.myanimelist.net/images/anime/1245/116760l.jpg",
    status: "Finished Airing",
    type: "Movie",
  },
  {
    name: "Hunter x Hunter (2011)",
    image: "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama'",
    image: "https://cdn.myanimelist.net/images/anime/4/50361l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama': Enchousen",
    image: "https://cdn.myanimelist.net/images/anime/1452/123686l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Ginga Eiyuu Densetsu",
    image: "https://cdn.myanimelist.net/images/anime/1976/142016l.jpg",
    status: "On going",
    type: "OVA",
  },
  {
    name: "Bleach: Sennen Kessen-hen",
    image: "https://cdn.myanimelist.net/images/anime/1908/135431l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    image: "https://cdn.myanimelist.net/images/anime/1160/122627l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama.",
    image: "https://cdn.myanimelist.net/images/anime/3/83528l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Fruits Basket: The Final",
    image: "https://cdn.myanimelist.net/images/anime/1085/114792l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama",
    image: "https://cdn.myanimelist.net/images/anime/10/73274l.jpg",
    status: "On going",
    type: "TV",
  },
  {
    name: "Clannad: After Story",
    image: "https://cdn.myanimelist.net/images/anime/1299/110774l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Koe no Katachi",
    image: "https://cdn.myanimelist.net/images/anime/1122/96435l.jpg",
    status: "Finished Airing",
    type: "Movie",
  },
  {
    name: "3-gatsu no Lion 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/3/88469l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Kusuriya no Hitorigoto",
    image: "https://cdn.myanimelist.net/images/anime/1708/138033l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
    image: "https://cdn.myanimelist.net/images/anime/10/51723l.jpg",
    status: "Finished Airing",
    type: "Movie",
  },
  {
    name: "Code Geass: Hangyaku no Lelouch R2",
    image: "https://cdn.myanimelist.net/images/anime/1088/135089l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    image: "https://cdn.myanimelist.net/images/anime/1279/131078l.jpg",
    status: "Finished Airing",
    type: "TV Special",
  },
  {
    name: "Boku no Kokoro no Yabai Yatsu 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1643/138581l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Gintama.: Shirogane no Tamashii-hen - Kouhan-sen",
    image: "https://cdn.myanimelist.net/images/anime/1776/96566l.jpg",
    status: "Finished Airing",
    type: "TV",
  },
  {
    name: "Monster",
    image: "https://cdn.myanimelist.net/images/anime/10/18793l.jpg",
    status: "On going",
    type: "TV",
  },
];

export type AnimeType = (typeof animeList)[0];
